name: Release jekyll-flant-plugins Gem

on:
  push:
    branches:
      - main
    paths:
      - '_gems/jekyll-flant-plugins/**'
jobs:
  build:
    name: Build, Publish and Release
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: ruby
          package-name: jekyll-flant-plugins
          bump-minor-pre-major: true
          version-file: "_gems/jekyll-flant-plugins/lib/jekyll-flant-plugins/version.rb"

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          cd _gems/jekyll-flant-plugins/
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        if: ${{ steps.release.outputs.release_created }}
